name: PR check!
on:
  push:
    branches:
      # - '*'
      # - '!main'
      - 'main'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # runs-on: macos-latest
    steps:
      - name: \[pre] V (checkout)
        uses: actions/checkout@v2
        with:
          repository: vlang/v
          path: v
      - name: \[pre] V (build)
        run: |
          make -j$(nproc)
          sudo v symlink
        working-directory: ./v

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: v -o derive bin/derive
      - name: Test
        run: v test examples/simple

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - name: \[pre] V (checkout)
        uses: actions/checkout@v2
        with:
          repository: vlang/v
          path: v
      - name: \[pre] V (build)
        run: |
          make -j$(nproc)
          sudo v symlink
        working-directory: ./v

      - name: Checkout
        uses: actions/checkout@v2

      - name: format
        run: v fmt -w .
      - name: Check modified
        run: git diff --exit-code
