name: Dev Report Discord
on:
  push:
    branches:
      - '*'
      - '!main'
env:
  REPO_DIR: repo
  DUMMY_HASH: 519157e
  HASH_STATE_FILE: last_hash

jobs:
  dev:
    name: Dev
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: exit 1
      - run: echo "should never run"

      - name: always()
        if: failure()
        run: echo -n "00112233" > ./${{ env.HASH_STATE_FILE }}

      - name: set prev hash
        if: failure()
        id: prev_hash
        run: echo "::set-output name=value::$(cat ./${{ env.HASH_STATE_FILE }})"
      - name: Report V_REPO Hash to Discord
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content": "${{ github.repository }} start failing after \"${{ steps.prev_hash.outputs.value }}\" .. \"${{ env.DUMMY_HASH }}\" ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"}' $DISCORD_WEBHOOK_URL
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
