name: V Compatibility Check!
on:
  # schedule:
  #   - cron: '*/2 * * * *'
  push:
    branches:
      - "main"

env:
  REPO_DIR: repo

jobs:
  check-hash:
    name: Check HASH
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.is-last-hash.outputs.cache-hit }}
    steps:
      - name: Get V repo latest hash
        id: v-latest-hash
        run: echo "::set-output name=value::$(git ls-remote https://github.com/vlang/v.git master | awk '{ print $1 }')"
        timeout-minutes: 2
      - name: Check cache with hash
        id: is-last-hash
        uses: actions/cache@v2
        with:
          path: ./
          key: ${{ steps.v-latest-hash.outputs.value }}
      # - name: Force exit if cache found
      #   if: steps.is-last-hash.outputs.cache-hit == 'true'
      #   run: exit 1
      - name: new commits in V?
        if: steps.is-last-hash.outputs.cache-hit != 'true'
        uses: ./.github/actions/compat-check.yml
