name: V Compatibility Check!
on:
  # schedule:
  #   - cron: '*/2 * * * *'
  push:
    branches:
      - "main"

env:
  REPO_DIR: repo

jobs:
  check-hash:
    name: Check HASH
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.v_latest_hash.outputs.changed || steps.s2.output.changed }}
      hash: ${{ steps.v_latest_hash.outputs.value || steps.s2.output.value }}
    steps:
      - name: Load latest hash
        id: last-hash
        uses: actions/cache@v2
        with:
          path: ./last_hash
          key: last_hash

      - name: Get V repo latest hash
        id: v_latest_hash
        run: |
          the_last_hash=$(git ls-remote https://github.com/vlang/v.git master | awk '{ print $1 }')
          echo "::set-output name=value::$(the_last_hash)"
          if [ $the_last_hash == $(cat ./last_hash) ]; then 
            echo "::set-output name=changed::true"
          fi
        # run: git ls-remote https://github.com/vlang/v.git master | awk '{ print $1 }'
        timeout-minutes: 1
      - name: fallback s1
        if: steps.v_latest_hash.conclusion == 'failure'
        uses: actions/checkout@v2
        with:
          repository: vlang/v
          path: v
      - name: fallback s2
        id: s2
        if: steps.v_latest_hash.conclusion == 'failure'
        run: |
          the_last_hash=$(git rev-parse HEAD)
          echo "::set-output name=value::$(the_last_hash)"
          if [ $the_last_hash == $(cat ./last_hash) ]; then 
            echo "::set-output name=changed::true"
          fi

      # - name: Check cache with hash
      #   id: is-last-hash
      #   uses: actions/cache@v2
      #   with:
      #     path: ./
      #     key: ${{ steps.v_latest_hash.outputs.value }}
      # - name: Force exit if cache found
      #   if: steps.is-last-hash.outputs.cache-hit == 'true'
      #   run: exit 1
      # - name: new commits in V?
      #   if: steps.is-last-hash.outputs.cache-hit != 'true'

  compat-check:
    # As this action is for checking V. compatibility,
    # no need to run further jobs if V repo doesn't changed.
    needs: [check-hash]
    # if: needs.check-hash.steps.is-last-hash.outputs.cache-hit != 'true'
    if: needs.check-hash.outputs.changed == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Load latest hash
        id: last-hash
        uses: actions/cache@v2
        with:
          path: ./last_hash
          key: last_hash
      - name: \[pre] V (checkout)
        uses: actions/checkout@v2
        with:
          repository: vlang/v
          path: v
      - name: \[pre] V (build)
          # make -j$(sysctl -n hw.logicalcpu)
        run: |
          make -j$(nproc)
          sudo ./v symlink
        working-directory: ./v

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.REPO_DIR }}

      - name: Run
        run: v run main.v
        working-directory: ${{ env.REPO_DIR }}

      - name: Update state
        run: echo -n "${{needs.check-hash.outputs.hash}}" > ./last_hash
      # - name: Build
      #   run: v -o derive bin/derive
      #   working-directory: ${{ env.REPO_DIR }}
      # - name: Test
      #   run: v test examples/simple
      #   working-directory: ${{ env.REPO_DIR }}
